[package]
name = "mod_tile_rs"
version = "0.1.0"
authors = ["Kean H Lau <khklau@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
bindgen = "0.57.0"

[dependencies]
libc = "0.2.0"
