[build]
rustflags = [
    "-C", "link-args=-Wl,--as-needed",
    "-C", "link-args=-Wl,-Bsymbolic-functions",
    "-C", "link-args=-Wl,-z,relro",
    "-C", "link-args=-Wl,-z,now",
    "-C", "link-args=-Wl,-rpath,/usr/lib/apache2/modules"]
 