GRANT ALL PRIVILEGES ON DATABASE osm TO osm;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO osm;

CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS hstore;

ALTER TABLE spatial_ref_sys OWNER TO osm;
